workspace(name="com_github_anapaya_vpp_build")
load(":repositories.bzl", "vpp_repositories")
vpp_repositories()
load(":deps.bzl", "vpp_deps")
vpp_deps()
load('@vpp_python_deps//:requirements.bzl', 'pip_install')
pip_install()
