typedef enum {
   VL_API_COP_INTERFACE_ENABLE_DISABLE,
   VL_API_COP_INTERFACE_ENABLE_DISABLE_REPLY,
   VL_API_COP_WHITELIST_ENABLE_DISABLE,
   VL_API_COP_WHITELIST_ENABLE_DISABLE_REPLY,
   VL_MSG_FIRST_AVAILABLE
} vl_api_cop_enum_t;
