typedef enum {
   VL_API_PG_CREATE_INTERFACE,
   VL_API_PG_CREATE_INTERFACE_REPLY,
   VL_API_PG_CAPTURE,
   VL_API_PG_CAPTURE_REPLY,
   VL_API_PG_ENABLE_DISABLE,
   VL_API_PG_ENABLE_DISABLE_REPLY,
   VL_MSG_FIRST_AVAILABLE
} vl_api_pg_enum_t;
