typedef enum {
   VL_API_DHCP6_PD_CLIENT_ENABLE_DISABLE,
   VL_API_DHCP6_PD_CLIENT_ENABLE_DISABLE_REPLY,
   VL_API_IP6_ADD_DEL_ADDRESS_USING_PREFIX,
   VL_API_IP6_ADD_DEL_ADDRESS_USING_PREFIX_REPLY,
   VL_MSG_FIRST_AVAILABLE
} vl_api_dhcp6_pd_client_cp_enum_t;
