typedef enum {
   VL_API_SVS_PLUGIN_GET_VERSION,
   VL_API_SVS_PLUGIN_GET_VERSION_REPLY,
   VL_API_SVS_TABLE_ADD_DEL,
   VL_API_SVS_TABLE_ADD_DEL_REPLY,
   VL_API_SVS_ROUTE_ADD_DEL,
   VL_API_SVS_ROUTE_ADD_DEL_REPLY,
   VL_API_SVS_ENABLE_DISABLE,
   VL_API_SVS_ENABLE_DISABLE_REPLY,
   VL_API_SVS_DUMP,
   VL_API_SVS_DETAILS,
   VL_MSG_FIRST_AVAILABLE
} vl_api_svs_enum_t;
