typedef enum {
   VL_API_SR_MPLS_POLICY_ADD,
   VL_API_SR_MPLS_POLICY_ADD_REPLY,
   VL_API_SR_MPLS_POLICY_MOD,
   VL_API_SR_MPLS_POLICY_MOD_REPLY,
   VL_API_SR_MPLS_POLICY_DEL,
   VL_API_SR_MPLS_POLICY_DEL_REPLY,
   VL_API_SR_MPLS_STEERING_ADD_DEL,
   VL_API_SR_MPLS_STEERING_ADD_DEL_REPLY,
   VL_API_SR_MPLS_POLICY_ASSIGN_ENDPOINT_COLOR,
   VL_API_SR_MPLS_POLICY_ASSIGN_ENDPOINT_COLOR_REPLY,
   VL_MSG_FIRST_AVAILABLE
} vl_api_sr_mpls_enum_t;
