typedef enum {
   VL_API_CREATE_VHOST_USER_IF,
   VL_API_CREATE_VHOST_USER_IF_REPLY,
   VL_API_MODIFY_VHOST_USER_IF,
   VL_API_MODIFY_VHOST_USER_IF_REPLY,
   VL_API_DELETE_VHOST_USER_IF,
   VL_API_DELETE_VHOST_USER_IF_REPLY,
   VL_API_SW_INTERFACE_VHOST_USER_DETAILS,
   VL_API_SW_INTERFACE_VHOST_USER_DUMP,
   VL_MSG_FIRST_AVAILABLE
} vl_api_vhost_user_enum_t;
