typedef enum {
   VL_API_TRACE_PROFILE_ADD,
   VL_API_TRACE_PROFILE_ADD_REPLY,
   VL_API_TRACE_PROFILE_DEL,
   VL_API_TRACE_PROFILE_DEL_REPLY,
   VL_API_TRACE_PROFILE_SHOW_CONFIG,
   VL_API_TRACE_PROFILE_SHOW_CONFIG_REPLY,
   VL_MSG_FIRST_AVAILABLE
} vl_api_trace_enum_t;
