typedef enum {
   VL_API_NSIM_CROSS_CONNECT_ENABLE_DISABLE,
   VL_API_NSIM_CROSS_CONNECT_ENABLE_DISABLE_REPLY,
   VL_API_NSIM_OUTPUT_FEATURE_ENABLE_DISABLE,
   VL_API_NSIM_OUTPUT_FEATURE_ENABLE_DISABLE_REPLY,
   VL_API_NSIM_CONFIGURE,
   VL_API_NSIM_CONFIGURE_REPLY,
   VL_MSG_FIRST_AVAILABLE
} vl_api_nsim_enum_t;
