typedef enum {
   VL_API_FLOWPROBE_TX_INTERFACE_ADD_DEL,
   VL_API_FLOWPROBE_TX_INTERFACE_ADD_DEL_REPLY,
   VL_API_FLOWPROBE_PARAMS,
   VL_API_FLOWPROBE_PARAMS_REPLY,
   VL_MSG_FIRST_AVAILABLE
} vl_api_flowprobe_enum_t;
